name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Connexion au registre privé
      - name: Log in to Private Registry
        uses: docker/login-action@v2
        with:
          registry: registry.example.com
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

      # Build et push vers Docker Hub
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/flaskapp:latest
            ${{ secrets.DOCKER_USERNAME }}/flaskapp:${{ github.sha }}

      # Build et push vers registre privé
      - name: Build and push to Private Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            registry.example.com/flaskapp:latest
            registry.example.com/flaskapp:${{ github.sha }}

      - name: Send mail on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: CI Pipeline Failed - ${{ github.repository }}
          to: tayeedoundjobi@gmail.com
          from: GitHub Actions
          body: |
            Le pipeline CI a échoué pour le commit ${{ github.sha }}.
            
            Branche: ${{ github.ref }}
            Auteur: ${{ github.actor }}
            
            Consultez les logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
